'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SlingshotDB.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property GHMYSQL_Command() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GHMYSQL_Command", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GHMYSQL_MySQLConnect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GHMYSQL_MySQLConnect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GHMySQL_Query() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GHMySQL_Query", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GHODBC_Command() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GHODBC_Command", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GHODBC_PostgresConnect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GHODBC_PostgresConnect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GHODBC_Query() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GHODBC_Query", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GHOLEDB_Command() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GHOLEDB_Command", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GHOLEDB_ExcelConnect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GHOLEDB_ExcelConnect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GHOLEDB_Query() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GHOLEDB_Query", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GHSQLite_Command() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GHSQLite_Command", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GHSQLite_CreateDB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GHSQLite_CreateDB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GHSQLite_Query() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GHSQLite_Query", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLCOM_CreateColumn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLCOM_CreateColumn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLCOM_CreateColumnAfter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLCOM_CreateColumnAfter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLCOM_CreateDatabase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLCOM_CreateDatabase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLCOM_CreateTable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLCOM_CreateTable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLCOM_Insert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLCOM_Insert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLCOM_Truncate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLCOM_Truncate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLQUERY_ColumnList() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLQUERY_ColumnList", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLQUERY_DatabaseList() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLQUERY_DatabaseList", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLQUERY_Select() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLQUERY_Select", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLQUERY_TableList() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLQUERY_TableList", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLUTIL_ColumnParameter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLUTIL_ColumnParameter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLUTIL_CreateGenomeDb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLUTIL_CreateGenomeDb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLUTIL_CreateLineDb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLUTIL_CreateLineDb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLUTIL_CreateLnsDB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLUTIL_CreateLnsDB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLUTIL_CreateMeshDB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLUTIL_CreateMeshDB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLUTIL_CreatePtsDB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLUTIL_CreatePtsDB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLUTIL_CreateSensorDb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLUTIL_CreateSensorDb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLUTIL_FormatRows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLUTIL_FormatRows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLUtility_DeSerialize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLUtility_DeSerialize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SQLUtility_Serialize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SQLUtility_Serialize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UTIL_RhinoPack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UTIL_RhinoPack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UTIL_RhinoUnpack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UTIL_RhinoUnpack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEB_FtpDownload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEB_FtpDownload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEB_FtpUpload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEB_FtpUpload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEB_HTTPReader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEB_HTTPReader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WEB_TwitterSearch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WEB_TwitterSearch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
